name: SuperCity
version: 1.0
main: com.supercity.main.SuperCity

commands:
  getCustomItem:
    description: "Get a custom item!"
    usage: "/getCustomItem <item_loc_name>"
  dontSkipNight:
    description: "Disables one-player-sleep for one night"
    usage: "/dontskipnight"
  enableOnePlayerSleep:
    description: "Re enables on-player-sleep!"
    usage: "/enableoneplayersleep"
  recording:
    description: "Toggles recording mode for youtubers!"
    usage: "/recording"
    aliases: ["rec"]
  togglescoreboard:
    description: "Toggles the sidebar scoreboard!"
    usage: "/togglescoreboard"
    aliases: ["togglesb"]
  togglechat:
    description: "Toggles the visibility of chat messages from other players!"
    usage: "/togglechat"
    aliases: ["togglechat","silent"]
  customEnchant:
    description: "Enchants held item of the executor with custom enchantment <id> of level [level]"
    usage: "/customenchant <id> [level]"
    aliases: ["customench"]
  getBackpack:
    description: "Get a backpack with a set id"
    usage: "/getbackpack <id>"
    aliases: ["backpack"]
  creeper:
    description: "Checks if a block was exploded by a creeper and who caused that."
    usage: "/creeper"
    aliases: ["whoexploded","creeperinfo"]
