name: ExtronPlus
version: 0.1
main: com.redsponge.extron.plus.ExtronPlus

commands:
  getCustomItem:
    description: "Get a custom item!"
    usage: "/getCustomItem <item_loc_name>"
  dontSkipNight:
    description: "Disables one-player-sleep for one night"
    usage: "/dontskipnight"
  enableOnePlayerSleep:
    description: "Re enables on-player-sleep!"
    usage: "/enableoneplayersleep"
